# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_uat do
    build_app(scheme: "SamplesApp",
              workspace: "SamplesApp.xcworkspace",
              include_bitcode: false,
              configuration: "Uat",
              clean: true,
              export_method: "app-store",
              export_options: {
                provisioningProfiles: { 
                  "com.renjun.photo" => "photo_appstore",
                },
                signingCertificate: "iPhone Distribution: Xiaoyan Yang (Z7CS86CU9Z)"
              },
              output_directory: "./build/packages",
              output_name: "SamplesApp-prod.ipa")
  end

  lane :build_prod do
    build_app(scheme: "SamplesApp",
              workspace: "SamplesApp.xcworkspace",
              include_bitcode: false,
              configuration: "Prod",
              clean: true,
              export_method: "ad-hoc",
              export_options: {
                provisioningProfiles: { 
                  "com.renjun.photo" => "adhoc",
                },
                signingCertificate: "iPhone Distribution: Xiaoyan Yang (Z7CS86CU9Z)"
              },
              output_directory: "./build/packages",
              output_name: "SamplesApp-uat.ipa")
  end

  lane :unit_tests do 
    run_tests(
      workspace: "SamplesApp.xcworkspace",
      scheme: "All-Tests",
      output_directory: "./build/tests",
      code_coverage: true,
      clean: true,
      skip_slack: true
    )
    coverage_report()
  end

  lane :coverage_report do
    coverage_path = "build/tests/coverage"
    # sh "rm -rf ../#{coverage_path}/*"
    xcov(
      workspace: "SamplesApp.xcworkspace",
      scheme: "All-Tests",
      configuration: "Uat",
      minimum_coverage_percentage: 30.0,
      output_directory: coverage_path,
      markdown_report: true,
      disable_coveralls: true,
      skip_slack: true
    )
  end

  lane :static_code_check do
    lint_base({:mode => :lint})
  end

  lane :static_code_correct do
    lint_base({:mode => :fix})
  end

  private_lane :lint_base do |options|
    swiftlint(
      mode: options[:mode],
      strict: true,
      executable: "./Pods/SwiftLint/swiftlint",
      config_file: "./.swiftlint.yml",
      output_file: "./fastlane/swiftlint_report.md",
      reporter: "markdown",
      raise_if_swiftlint_error: true,   
      ignore_exit_status: true
    )
  end

  lane :release_to_test_channel do
    desc "release_to_test_channel"
  end

  lane :release_to_testflight do 
    build_prod
    api_key = apple_api_key()
    upload_to_testflight(
      api_key: api_key,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end

  lane :release_to_testflight_mock do 
    build_prod
    puts "mock testflight sucess"
  end

  private_lane :apple_api_key do
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_API_ISSUER_ID'],
      key_filepath: ENV['APPLE_API_KEY_FILEPATH'],
      duration: 1200,
      in_house: false
    )
  end

end
